# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: 'test'
  displayName: 'Build and test'
  strategy:
    matrix:
      linux:
        imageName: 'Ubuntu-16.04'
      mac:
        imageName: 'macOS-10.13'
      windows:
        imageName: 'win1803'
  pool:
    vmImage: $(imageName)
  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '10.x'

  - script: |
      npm ci
    displayName: 'Install packages'

  - script: |
      npm run build-client
    displayName: 'Build'
  - script: |
      npm run test
    displayName: 'Test'

  - powershell: |
      npm run test-integration-win
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: 'Test Integration Windows'
    env:
      PERCY_TOKEN: $(PERCY_TOKEN)

  - script: |
      npm run test-integration
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    displayName: 'Test Integration'

- job: 'release'
  displayName: 'Release'
  dependsOn: 'test'
  strategy:
    matrix:
      linux:
        imageName: 'Ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '10.x'
  - script: |
      npm ci
    displayName: 'Install packages'
  - script: |
      npx semantic-release
    displayName: 'Release'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      NPM_TOKEN: $(NPM_TOKEN)
